/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SafetyIndexRouteImport } from './routes/safety/index'
import { Route as RidesIndexRouteImport } from './routes/rides/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as InterimSkipperQuizIndexRouteImport } from './routes/interim-skipper-quiz/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as FishingChartersIndexRouteImport } from './routes/fishing-charters/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BoatRideIndexRouteImport } from './routes/boat-ride/index'
import { Route as AddOnsIndexRouteImport } from './routes/add-ons/index'
import { Route as BookingsIndexRouteImport } from './routes/Bookings/index'
import { Route as PaymentsSuccessRouteImport } from './routes/payments/success'
import { Route as PaymentsResultRouteImport } from './routes/payments/result'
import { Route as PaymentsFailedRouteImport } from './routes/payments/failed'
import { Route as PaymentsCancelledRouteImport } from './routes/payments/cancelled'
import { Route as AdminQuizRouteImport } from './routes/admin/quiz'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as WeatherCalmSlotsIndexRouteImport } from './routes/weather/calm-slots/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/safety/',
  path: '/safety/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterimSkipperQuizIndexRoute = InterimSkipperQuizIndexRouteImport.update({
  id: '/interim-skipper-quiz/',
  path: '/interim-skipper-quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingChartersIndexRoute = FishingChartersIndexRouteImport.update({
  id: '/fishing-charters/',
  path: '/fishing-charters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoatRideIndexRoute = BoatRideIndexRouteImport.update({
  id: '/boat-ride/',
  path: '/boat-ride/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnsIndexRoute = AddOnsIndexRouteImport.update({
  id: '/add-ons/',
  path: '/add-ons/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/Bookings/',
  path: '/Bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsResultRoute = PaymentsResultRouteImport.update({
  id: '/payments/result',
  path: '/payments/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailedRoute = PaymentsFailedRouteImport.update({
  id: '/payments/failed',
  path: '/payments/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsCancelledRoute = PaymentsCancelledRouteImport.update({
  id: '/payments/cancelled',
  path: '/payments/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizRoute = AdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const WeatherCalmSlotsIndexRoute = WeatherCalmSlotsIndexRouteImport.update({
  id: '/weather/calm-slots/',
  path: '/weather/calm-slots/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings': typeof BookingsIndexRoute
  '/add-ons': typeof AddOnsIndexRoute
  '/boat-ride': typeof BoatRideIndexRoute
  '/contact': typeof ContactIndexRoute
  '/fishing-charters': typeof FishingChartersIndexRoute
  '/home': typeof HomeIndexRoute
  '/interim-skipper-quiz': typeof InterimSkipperQuizIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/rides': typeof RidesIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/weather/calm-slots': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings': typeof BookingsIndexRoute
  '/add-ons': typeof AddOnsIndexRoute
  '/boat-ride': typeof BoatRideIndexRoute
  '/contact': typeof ContactIndexRoute
  '/fishing-charters': typeof FishingChartersIndexRoute
  '/home': typeof HomeIndexRoute
  '/interim-skipper-quiz': typeof InterimSkipperQuizIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/rides': typeof RidesIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/weather/calm-slots': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings/': typeof BookingsIndexRoute
  '/add-ons/': typeof AddOnsIndexRoute
  '/boat-ride/': typeof BoatRideIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/fishing-charters/': typeof FishingChartersIndexRoute
  '/home/': typeof HomeIndexRoute
  '/interim-skipper-quiz/': typeof InterimSkipperQuizIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/weather/calm-slots/': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/overview'
    | '/admin/quiz'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings'
    | '/add-ons'
    | '/boat-ride'
    | '/contact'
    | '/fishing-charters'
    | '/home'
    | '/interim-skipper-quiz'
    | '/locations'
    | '/privacy'
    | '/rides'
    | '/safety'
    | '/terms'
    | '/weather'
    | '/weather/calm-slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/overview'
    | '/admin/quiz'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings'
    | '/add-ons'
    | '/boat-ride'
    | '/contact'
    | '/fishing-charters'
    | '/home'
    | '/interim-skipper-quiz'
    | '/locations'
    | '/privacy'
    | '/rides'
    | '/safety'
    | '/terms'
    | '/weather'
    | '/weather/calm-slots'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/overview'
    | '/admin/quiz'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings/'
    | '/add-ons/'
    | '/boat-ride/'
    | '/contact/'
    | '/fishing-charters/'
    | '/home/'
    | '/interim-skipper-quiz/'
    | '/locations/'
    | '/privacy/'
    | '/rides/'
    | '/safety/'
    | '/terms/'
    | '/weather/'
    | '/weather/calm-slots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PaymentsCancelledRoute: typeof PaymentsCancelledRoute
  PaymentsFailedRoute: typeof PaymentsFailedRoute
  PaymentsResultRoute: typeof PaymentsResultRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  AddOnsIndexRoute: typeof AddOnsIndexRoute
  BoatRideIndexRoute: typeof BoatRideIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FishingChartersIndexRoute: typeof FishingChartersIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InterimSkipperQuizIndexRoute: typeof InterimSkipperQuizIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
  WeatherCalmSlotsIndexRoute: typeof WeatherCalmSlotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/': {
      id: '/safety/'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interim-skipper-quiz/': {
      id: '/interim-skipper-quiz/'
      path: '/interim-skipper-quiz'
      fullPath: '/interim-skipper-quiz'
      preLoaderRoute: typeof InterimSkipperQuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing-charters/': {
      id: '/fishing-charters/'
      path: '/fishing-charters'
      fullPath: '/fishing-charters'
      preLoaderRoute: typeof FishingChartersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boat-ride/': {
      id: '/boat-ride/'
      path: '/boat-ride'
      fullPath: '/boat-ride'
      preLoaderRoute: typeof BoatRideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ons/': {
      id: '/add-ons/'
      path: '/add-ons'
      fullPath: '/add-ons'
      preLoaderRoute: typeof AddOnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Bookings/': {
      id: '/Bookings/'
      path: '/Bookings'
      fullPath: '/Bookings'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/result': {
      id: '/payments/result'
      path: '/payments/result'
      fullPath: '/payments/result'
      preLoaderRoute: typeof PaymentsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failed': {
      id: '/payments/failed'
      path: '/payments/failed'
      fullPath: '/payments/failed'
      preLoaderRoute: typeof PaymentsFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/cancelled': {
      id: '/payments/cancelled'
      path: '/payments/cancelled'
      fullPath: '/payments/cancelled'
      preLoaderRoute: typeof PaymentsCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quiz': {
      id: '/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AdminQuizRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/weather/calm-slots/': {
      id: '/weather/calm-slots/'
      path: '/weather/calm-slots'
      fullPath: '/weather/calm-slots'
      preLoaderRoute: typeof WeatherCalmSlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminQuizRoute: typeof AdminQuizRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminQuizRoute: AdminQuizRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PaymentsCancelledRoute: PaymentsCancelledRoute,
  PaymentsFailedRoute: PaymentsFailedRoute,
  PaymentsResultRoute: PaymentsResultRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  AddOnsIndexRoute: AddOnsIndexRoute,
  BoatRideIndexRoute: BoatRideIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FishingChartersIndexRoute: FishingChartersIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  InterimSkipperQuizIndexRoute: InterimSkipperQuizIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
  SafetyIndexRoute: SafetyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  WeatherIndexRoute: WeatherIndexRoute,
  WeatherCalmSlotsIndexRoute: WeatherCalmSlotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
