/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather/index'
import { Route as SafetyIndexRouteImport } from './routes/safety/index'
import { Route as RidesIndexRouteImport } from './routes/rides/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as InterimSkipperQuizIndexRouteImport } from './routes/interim-skipper-quiz/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AddOnsIndexRouteImport } from './routes/add-ons/index'
import { Route as BookingsIndexRouteImport } from './routes/Bookings/index'
import { Route as PaymentsSuccessRouteImport } from './routes/payments/success'
import { Route as PaymentsResultRouteImport } from './routes/payments/result'
import { Route as PaymentsFailedRouteImport } from './routes/payments/failed'
import { Route as PaymentsCancelledRouteImport } from './routes/payments/cancelled'
import { Route as WeatherCalmSlotsIndexRouteImport } from './routes/weather/calm-slots/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/safety/',
  path: '/safety/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterimSkipperQuizIndexRoute = InterimSkipperQuizIndexRouteImport.update({
  id: '/interim-skipper-quiz/',
  path: '/interim-skipper-quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnsIndexRoute = AddOnsIndexRouteImport.update({
  id: '/add-ons/',
  path: '/add-ons/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/Bookings/',
  path: '/Bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsResultRoute = PaymentsResultRouteImport.update({
  id: '/payments/result',
  path: '/payments/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailedRoute = PaymentsFailedRouteImport.update({
  id: '/payments/failed',
  path: '/payments/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsCancelledRoute = PaymentsCancelledRouteImport.update({
  id: '/payments/cancelled',
  path: '/payments/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherCalmSlotsIndexRoute = WeatherCalmSlotsIndexRouteImport.update({
  id: '/weather/calm-slots/',
  path: '/weather/calm-slots/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings': typeof BookingsIndexRoute
  '/add-ons': typeof AddOnsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/home': typeof HomeIndexRoute
  '/interim-skipper-quiz': typeof InterimSkipperQuizIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/rides': typeof RidesIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/weather/calm-slots': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings': typeof BookingsIndexRoute
  '/add-ons': typeof AddOnsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/home': typeof HomeIndexRoute
  '/interim-skipper-quiz': typeof InterimSkipperQuizIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/rides': typeof RidesIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/weather/calm-slots': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payments/cancelled': typeof PaymentsCancelledRoute
  '/payments/failed': typeof PaymentsFailedRoute
  '/payments/result': typeof PaymentsResultRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/Bookings/': typeof BookingsIndexRoute
  '/add-ons/': typeof AddOnsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/home/': typeof HomeIndexRoute
  '/interim-skipper-quiz/': typeof InterimSkipperQuizIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/weather/calm-slots/': typeof WeatherCalmSlotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings'
    | '/add-ons'
    | '/admin'
    | '/contact'
    | '/home'
    | '/interim-skipper-quiz'
    | '/locations'
    | '/rides'
    | '/safety'
    | '/weather'
    | '/weather/calm-slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings'
    | '/add-ons'
    | '/admin'
    | '/contact'
    | '/home'
    | '/interim-skipper-quiz'
    | '/locations'
    | '/rides'
    | '/safety'
    | '/weather'
    | '/weather/calm-slots'
  id:
    | '__root__'
    | '/'
    | '/payments/cancelled'
    | '/payments/failed'
    | '/payments/result'
    | '/payments/success'
    | '/Bookings/'
    | '/add-ons/'
    | '/admin/'
    | '/contact/'
    | '/home/'
    | '/interim-skipper-quiz/'
    | '/locations/'
    | '/rides/'
    | '/safety/'
    | '/weather/'
    | '/weather/calm-slots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentsCancelledRoute: typeof PaymentsCancelledRoute
  PaymentsFailedRoute: typeof PaymentsFailedRoute
  PaymentsResultRoute: typeof PaymentsResultRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  AddOnsIndexRoute: typeof AddOnsIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InterimSkipperQuizIndexRoute: typeof InterimSkipperQuizIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
  WeatherCalmSlotsIndexRoute: typeof WeatherCalmSlotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/': {
      id: '/safety/'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interim-skipper-quiz/': {
      id: '/interim-skipper-quiz/'
      path: '/interim-skipper-quiz'
      fullPath: '/interim-skipper-quiz'
      preLoaderRoute: typeof InterimSkipperQuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ons/': {
      id: '/add-ons/'
      path: '/add-ons'
      fullPath: '/add-ons'
      preLoaderRoute: typeof AddOnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Bookings/': {
      id: '/Bookings/'
      path: '/Bookings'
      fullPath: '/Bookings'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/result': {
      id: '/payments/result'
      path: '/payments/result'
      fullPath: '/payments/result'
      preLoaderRoute: typeof PaymentsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failed': {
      id: '/payments/failed'
      path: '/payments/failed'
      fullPath: '/payments/failed'
      preLoaderRoute: typeof PaymentsFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/cancelled': {
      id: '/payments/cancelled'
      path: '/payments/cancelled'
      fullPath: '/payments/cancelled'
      preLoaderRoute: typeof PaymentsCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/calm-slots/': {
      id: '/weather/calm-slots/'
      path: '/weather/calm-slots'
      fullPath: '/weather/calm-slots'
      preLoaderRoute: typeof WeatherCalmSlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentsCancelledRoute: PaymentsCancelledRoute,
  PaymentsFailedRoute: PaymentsFailedRoute,
  PaymentsResultRoute: PaymentsResultRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  AddOnsIndexRoute: AddOnsIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  InterimSkipperQuizIndexRoute: InterimSkipperQuizIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
  SafetyIndexRoute: SafetyIndexRoute,
  WeatherIndexRoute: WeatherIndexRoute,
  WeatherCalmSlotsIndexRoute: WeatherCalmSlotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
